export const PROJECTS_DATA = [
    {
        id: 1,
        title: "My Clinic - MERN App",
        description: "This project is a Full Stack MERN application for a private clinic. It focuses on providing a secure and user-friendly interface for booking and manage visits.",
        image: "/images/portfolio/myclinic.png",
        tag: ["All", "Full Stack"],
        gitUrl: "https://github.com/diegoddie/S2I_FullStack_FinalProject_MERNclinic",
        previewUrl: "www.myclinic.tech",
    },
    {
        id: 2,
        title: "Hilink - Travel Next.js App",
        description: "This is a landing page for a travel app built using Next.js",
        image: "/images/portfolio/travel_frontend.png",
        tag: ["All", "Front End"],
        gitUrl: "https://github.com/diegoddie/NextJS_TravelApp_UIUX",
        previewUrl: "https://next-js-travel-app-uiux.vercel.app/",
    },
    {
        id: 3,
        title: "Crowdfunding Dapp",
        description: "Web3Raise is a decentralized crowdfunding platform built on top of Ethereum blockchain. It allows users to create and fund campaigns for their projects using smart contracts.",
        image: "/images/portfolio/CrowdfundingDapp.png",
        tag: ["All", "Blockchain"],
        gitUrl: "https://github.com/diegoddie/Web3Raise-CrowdfundingDapp",
        previewUrl: "https://web3-raise-crowdfunding-dapp.vercel.app/",
    },
    {
        id: 4,
        title: "GreenEats",
        description: "With the power of Spoonacular APIs, this app allows you to explore a world of mouthwatering recipes, save your favorites, create custom meal plans, search for specific ingredients, and more.",
        image: "/images/portfolio/greeneats.png",
        tag: ["All", "Full Stack"],
        gitUrl: "https://github.com/diegoddie/greenEats_S2I_FullStack_React",
        previewUrl: "https://greeneats-s2i.vercel.app/",
    },
    {
        id: 5,
        title: "MERN Auth Template",
        description: "This is a full-stack app built with the MERN stack. It provides authentication features, allowing users to sign up, log in, and log out, with access to protected routes exclusively for authenticated users.",
        image: "/images/portfolio/mernauth.png",
        tag: ["All", "Full Stack"],
        gitUrl: "https://github.com/diegoddie/MERN_Auth",
        previewUrl: "https://mern-auth-q1qf.onrender.com/",
    },
    {
        id: 6,
        title: "Fauxica Store Landing Page",
        description: "This is a landing page for an e-commerce, built with HTML and CSS",
        image: "/images/portfolio/Fauxica.png",
        tag: ["All", "Front End"],
        gitUrl: "https://github.com/diegoddie/FrontEnd_LandingPage",
        previewUrl: "https://fauxicastore.netlify.app/",
    },
    {
        id: 7,
        title: "Concept Nike Landing Page",
        description: "This is a concept nike landing page built with React and Tailwindcss.",
        image: "/images/portfolio/nike.png",
        tag: ["All", "Front End"],
        gitUrl: "https://github.com/diegoddie/Nike_Concept_Website-TailwindCSS",
        previewUrl: "https://nikeconceptwebsite.netlify.app/",
    },
    {
        id: 8,
        title: "Voting Dapp",
        description: "This is a decentralized voting application (DApp) built using Hardhat, Tailwind CSS, React, Solidity, and ThirdWeb.",
        image: "/images/portfolio/Votingdapp.png",
        tag: ["All", "Blockchain"],
        gitUrl: "https://github.com/diegoddie/Web3Raise-CrowdfundingDapp",
        previewUrl: "https://voting-dapp-start2-impact-project.vercel.app/",
    },
    {
        id: 9,
        title: "GreenStepBids",
        description: "Django project for an online auction application, allowing users to participate in auctions and place bids on sneakers. At the end of each auction, a JSON file containing comprehensive auction details is generated, hashed and securely transmitted to the Sepolia blockchain.",
        image: "/images/portfolio/greenstepbids.png",
        tag: ["All", "Blockchain"],
        gitUrl: "https://github.com/diegoddie/DJANGO_Start2Impact_FinalProject",
        previewUrl: "https://web-production-bbee.up.railway.app/",
    },
  ];